import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  tr: {
    appTitle: 'Vampir Köylü',
    createRoom: 'Oda Kur',
    joinRoom: 'Odaya Katıl',
    gameGuide: 'Oyun Rehberi',
    enterRoomCode: 'Oda Kodunu Girin',
    join: 'Katıl',
    roomCode: 'Oda Kodu',
    copyCode: 'Kodu Kopyala',
    waitingForPlayers: 'Oyuncular Bekleniyor...',
    startGame: 'Oyunu Başlat',
    ready: 'Hazır',
    notReady: 'Hazır Değil',
    players: 'Oyuncular',
    yourRole: 'Rolünüz',
    vampir: 'Vampir',
    koylu: 'Köylü',
    dayPhase: 'Gündüz',
    nightPhase: 'Gece',
    votingPhase: 'Oylama',
    selectTarget: 'Hedef Seçin',
    eliminate: 'Öldür',
    startVoting: 'Oylamayı Başlat',
    vote: 'Oy Ver',
    eliminated: 'Elendi',
    votingResults: 'Oylama Sonuçları',
    vampiresWin: 'Vampirler Kazandı!',
    villagersWin: 'Köylüler Kazandı!',
    playAgain: 'Tekrar Oyna',
    leaveRoom: 'Odadan Ayrıl',
    alive: 'Hayatta',
    dead: 'Öldü',
    endVoting: 'Oylamayı Bitir',
    endNight: 'Geceyi Bitir',
    guideTitle: 'Oyun Rehberi',
    guideIntro: 'Vampir Köylü, sosyal çıkarım ve stratejiye dayalı çok oyunculu bir oyundur.',
    guideRoles: 'Roller',
    guideVampir: 'Vampir: Her gece bir köylüyü öldürür. Kimliğini gizli tutmalıdır.',
    guideKoylu: 'Köylü: Vampiri bulmaya çalışır ve oylamalarla elemeye çalışır.',
    guideGameFlow: 'Oyun Akışı',
    guideDay: 'Gündüz: Tüm oyuncular tartışır ve şüphelenilen kişiyi belirler.',
    guideNight: 'Gece: Vampir bir kurban seçer.',
    guideVoting: 'Oylama: Oyuncular birini elemeye oy verir.',
    guideWinConditions: 'Kazanma Koşulları',
    guideVampiresWin: 'Vampirler: Köylü sayısı vampir sayısına eşit olursa kazanır.',
    guideVillagersWin: 'Köylüler: Tüm vampirleri elediklerinde kazanır.',
    close: 'Kapat',
    enterUsername: 'Kullanıcı Adı Girin',
    username: 'Kullanıcı Adı',
    continue: 'Devam Et',
    profile: 'Profil',
    stats: 'İstatistikler',
    gamesPlayed: 'Oynanan Oyunlar',
    gamesWon: 'Kazanılan Oyunlar',
    winRate: 'Kazanma Oranı',
    leaderboard: 'Sıralama',
    rank: 'Sıra',
    player: 'Oyuncu',
    wins: 'Kazanma',
    voiceChat: 'Sesli Sohbet',
    enableMic: 'Mikrofonu Aç',
    disableMic: 'Mikrofonu Kapat',
    morning: 'Sabah Oldu!',
    wasEliminated: 'elendi',
    discussTime: 'Tartışma Zamanı',
    chatPlaceholder: 'Mesaj yazın...',
    chat: 'Sohbet',
    you: 'Siz',
    noMessagesYet: 'Henüz mesaj yok...',
    chatDisabled: 'Şu an yazamazsınız',
    send: 'Gönder',
    voiceChatTitle: 'Sesli Katılımcılar',
    connecting: 'Bağlanıyor...',
    connected: 'Bağlandı',
    mute: 'Sustur',
    unmute: 'Sesi Aç',
    login: 'Giriş Yap',
    signUp: 'Kayıt Ol',
    email: 'E-posta',
    password: 'Şifre',
    enterEmail: 'E-posta adresinizi girin',
    authError: 'Kimlik doğrulama hatası',
    noAccount: 'Hesabınız yok mu? Kayıt olun',
    hasAccount: 'Zaten hesabınız var mı? Giriş yapın',
    editProfile: 'Profili Düzenle',
    logout: 'Çıkış Yap',
    back: 'Geri',
    topPlayers: 'En İyi Oyuncular',
    noPlayers: 'Henüz oyuncu yok',
  },
  en: {
    appTitle: 'Vampire Village',
    createRoom: 'Create Room',
    joinRoom: 'Join Room',
    gameGuide: 'Game Guide',
    enterRoomCode: 'Enter Room Code',
    join: 'Join',
    roomCode: 'Room Code',
    copyCode: 'Copy Code',
    waitingForPlayers: 'Waiting for Players...',
    startGame: 'Start Game',
    ready: 'Ready',
    notReady: 'Not Ready',
    players: 'Players',
    yourRole: 'Your Role',
    vampir: 'Vampire',
    koylu: 'Villager',
    dayPhase: 'Day',
    nightPhase: 'Night',
    votingPhase: 'Voting',
    selectTarget: 'Select Target',
    eliminate: 'Eliminate',
    startVoting: 'Start Voting',
    vote: 'Vote',
    eliminated: 'Eliminated',
    votingResults: 'Voting Results',
    vampiresWin: 'Vampires Win!',
    villagersWin: 'Villagers Win!',
    playAgain: 'Play Again',
    leaveRoom: 'Leave Room',
    alive: 'Alive',
    dead: 'Dead',
    endVoting: 'End Voting',
    endNight: 'End Night',
    guideTitle: 'Game Guide',
    guideIntro: 'Vampire Village is a multiplayer social deduction and strategy game.',
    guideRoles: 'Roles',
    guideVampir: 'Vampire: Eliminates one villager each night. Must keep identity hidden.',
    guideKoylu: 'Villager: Tries to find the vampire and eliminate them through voting.',
    guideGameFlow: 'Game Flow',
    guideDay: 'Day: All players discuss and identify suspects.',
    guideNight: 'Night: Vampire selects a victim.',
    guideVoting: 'Voting: Players vote to eliminate someone.',
    guideWinConditions: 'Win Conditions',
    guideVampiresWin: 'Vampires: Win when villagers equal or are fewer than vampires.',
    guideVillagersWin: 'Villagers: Win when all vampires are eliminated.',
    close: 'Close',
    enterUsername: 'Enter Username',
    username: 'Username',
    continue: 'Continue',
    profile: 'Profile',
    stats: 'Statistics',
    gamesPlayed: 'Games Played',
    gamesWon: 'Games Won',
    winRate: 'Win Rate',
    leaderboard: 'Leaderboard',
    rank: 'Rank',
    player: 'Player',
    wins: 'Wins',
    voiceChat: 'Voice Chat',
    enableMic: 'Enable Mic',
    disableMic: 'Disable Mic',
    morning: 'Morning Has Come!',
    wasEliminated: 'was eliminated',
    discussTime: 'Discussion Time',
    chatPlaceholder: 'Type a message...',
    chat: 'Chat',
    you: 'You',
    noMessagesYet: 'No messages yet...',
    chatDisabled: 'Chat is disabled',
    send: 'Send',
    voiceChatTitle: 'Voice Participants',
    connecting: 'Connecting...',
    connected: 'Connected',
    mute: 'Mute',
    unmute: 'Unmute',
    login: 'Login',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    enterEmail: 'Enter your email',
    authError: 'Authentication error',
    noAccount: "Don't have an account? Sign up",
    hasAccount: 'Already have an account? Login',
    editProfile: 'Edit Profile',
    logout: 'Logout',
    back: 'Back',
    topPlayers: 'Top Players',
    noPlayers: 'No players yet',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('tr');

  const t = (key: string): string => {
    const dict = (translations as any)[language] as Record<string, string>;
    return dict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
